### ISSUE TITLE
Add a first time initalize script that does everything

### ISSUE THREAD

**Issue by soumyaray** [codepraise/codepraise-devcontainer#11]
Prequisites:
- user must clone devcontainer
- user must cd into devcontainer folder

Script tasks:

- [ ] GUARDS
  - [ ] exit if code repos exist
  - [ ] exit if data stores exist
- [ ] clone the code repos
- [ ] startup the container (existing script -- but non-interactive?)
- [ ] bundle install inside the container
- [ ] write a message to user that in future they should run the startup script only
- [ ] leave user in the container

**Comment by tienyulin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ISSUE: Add Initialize Script #DevContainer](https://trello.com/c/34WhpjML/12-issue-add-initialize-script-devcontainer)

**Comment by tienyulin** [comment]
User doesn't have to run a initialize script for the first time, it integrates into the `load_profile`, so every time user runs `start-devcontainer.sh`, it will check whether the repo exists then clone the repo if not, and execute `bundle install` automatically.
