### ISSUE TITLE
Startup script additions

### ISSUE THREAD

**Issue by soumyaray** [codepraise/codepraise-devcontainer#12]
- [ ] tell user to bundle install if not yet done (can we check if bundled already?)

**Comment by tienyulin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ISSUE: Print Reminding Message in Startup Script #DevContainer](https://trello.com/c/Ce6vnno1/13-issue-print-reminding-message-in-startup-script-devcontainer)

**Comment by tienyulin** [comment]
Every time user runs `start-devcontainer.sh`, it will execute `bundle install` for each project automatically, no need to show the message.
