### ISSUE TITLE
Can we remove PASSWD required for .env?

### ISSUE THREAD

**Issue by soumyaray** [codepraise/codepraise-devcontainer#9]
Can everything just be done by editing dockerfile instead of using sudo?

**Comment by tienyulin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DEVELOP: DevContainer for CodePraise](https://trello.com/c/GDC22K31/7-develop-devcontainer-for-codepraise)

**Comment by tienyulin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/codepraise/codepraise-devcontainer/issues/9](https://trello.com/c/gBeecxDe/10-https-githubcom-codepraise-codepraise-devcontainer-issues-9)

**Comment by tienyulin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ISSUE: Remove PASSWD #DevContainer](https://trello.com/c/gBeecxDe/10-issue-remove-passwd-devcontainer)

**Comment by tienyulin** [comment]
Still leave `sudo` but remove the password for using `sudo`. it's a safety mechanism to alert the user that this behavior requires the highest privilege from the `root`; it might affect the system.
